## EQE511- Week04 | Hands-on Class

---

Topic

1. Frame system

2. Def for frame system

3. Assembling the system stiffness matrix

---

Frame member stiffness matrix in global coordinates

<img src="Figures/W04-1-FrameGlobalStiffness.png" height = 10>


**Solution FlowChart**

<img src="Figures/W04-0-FlowChartForFrame.svg" height = 10>


**Import the modules**

In [11]:
import numpy as np

---

**Let's create the FrameStiffness**

In [63]:
def FrameStiffness( E , A , I , I_node  , J_node):
    """
    Arguments:
    E : Modulus of elasticity (MPa = N/mm2)
    A : Area (mm2)
    I : Moment of inertia (mm4)
    I_Node (xi_1,xi_2) : Coordinates of node i (Tuple) 
    J_Node (xj_1,xj_2) : Coordinates of node j (Tuple) 
    
    Return: 
    Member Stiffness matrix
    """
    # Parse the node coordinates
    xi_1,xi_2 = I_node[0] , I_node[1]
    xj_1,xj_2 = J_node[0] , J_node[1]
    
    # Delta values
    delta_1 = xj_1 - xi_1
    delta_2 = xj_2 - xi_2
    
    # Length of member
    L_member = ((delta_1)**2 + (delta_2)**2 )**(0.5)
    
    # Repeating values
    EA_L3 = E * A / L_member**3
    EI_L5 = E * I / L_member**5
    EI_L3 = E * I / L_member**3
    EI_L  = E * I / L_member
    
    # Member stiffness matrix in array
    # Q1
    k_Q1 = np.array([[(EA_L3 * delta_1**2 + 12*EI_L5*delta_2**2) , (EA_L3-12*EI_L5)*delta_1*delta_2 ,(-6*EI_L3*delta_2)],
                     [(EA_L3-12*EI_L5)*delta_1*delta_2 , (EA_L3*delta_2**2 + 12*EI_L5*delta_1**2) , (6*EI_L3*delta_1) ],
                     [ (-6*EI_L3*delta_2) , (6*EI_L3*delta_1) , (4*EI_L) ]])
    # Q4 
    k_Q4 = np.array([[(EA_L3 * delta_1**2 + 12*EI_L5*delta_2**2) , (EA_L3-12*EI_L5)*delta_1*delta_2 ,(6*EI_L3*delta_2)],
                     [(EA_L3-12*EI_L5)*delta_1*delta_2 , (EA_L3*delta_2**2 + 12*EI_L5*delta_1**2) , (-6*EI_L3*delta_1) ],
                     [ (6*EI_L3*delta_2) , (-6*EI_L3*delta_1) , (4*EI_L) ]])
    # Q3
    
    k_Q3 = np.array([ [ -(EA_L3 * delta_1**2 + 12*EI_L5*delta_2**2) , -(EA_L3 - 12*EI_L5)*delta_1*delta_2 , (6*EI_L3*delta_2) ] ,
                    [ -(EA_L3 - 12*EI_L5)*delta_1*delta_2 , -(EA_L3 * delta_2**2 + 12*EI_L5*delta_1**2) , -(6*EI_L3*delta_1)],
                    [ -(6*EI_L3*delta_2) , (6*EI_L3*delta_1) , (2*EI_L)]])
    
    # Q2
    k_Q2 = np.transpose( np.array([ [ -(EA_L3 * delta_1**2 + 12*EI_L5*delta_2**2) , -(EA_L3 - 12*EI_L5)*delta_1*delta_2 , (6*EI_L3*delta_2) ] ,
                    [ -(EA_L3 - 12*EI_L5)*delta_1*delta_2 , -(EA_L3 * delta_2**2 + 12*EI_L5*delta_1**2) , -(6*EI_L3*delta_1)],
                    [ -(6*EI_L3*delta_2) , (6*EI_L3*delta_1) , (2*EI_L)]]))
    
    # Finally the member stiffness matrix
    K = np.array([[k_Q1] , [k_Q2],[k_Q3],[k_Q4]])

    # Return
    return K
    

**Let's do test for QA**

Unit test

In [20]:
K_Test1 = FrameStiffness( 1 , 1 , 1 , (0,0)  , (1,1))
print( K_Test1)

[[[[ 2.47487373 -1.76776695 -2.12132034]
   [-1.76776695  2.47487373  2.12132034]
   [-2.12132034  2.12132034  2.82842712]]]


 [[[-2.47487373  1.76776695  2.12132034]
   [ 1.76776695 -2.47487373 -2.12132034]
   [-2.12132034  2.12132034  1.41421356]]]


 [[[-2.47487373  1.76776695  2.12132034]
   [ 1.76776695 -2.47487373 -2.12132034]
   [-2.12132034  2.12132034  1.41421356]]]


 [[[ 2.47487373 -1.76776695  2.12132034]
   [-1.76776695  2.47487373 -2.12132034]
   [ 2.12132034 -2.12132034  2.82842712]]]]


In [24]:
K_Test2 = FrameStiffness(  0 , 1 , 1 , (0,0)  , (1,1))
print( K_Test2)

[[[[ 0.  0. -0.]
   [ 0.  0.  0.]
   [-0.  0.  0.]]]


 [[[-0. -0.  0.]
   [-0. -0. -0.]
   [-0.  0.  0.]]]


 [[[-0. -0.  0.]
   [-0. -0. -0.]
   [-0.  0.  0.]]]


 [[[ 0.  0.  0.]
   [ 0.  0. -0.]
   [ 0. -0.  0.]]]]


In [27]:
K_Test3 = FrameStiffness(  1 , 1 , 0 , (0,0)  , (1,1))
print( K_Test3)

[[[[ 0.35355339  0.35355339 -0.        ]
   [ 0.35355339  0.35355339  0.        ]
   [-0.          0.          0.        ]]]


 [[[-0.35355339 -0.35355339  0.        ]
   [-0.35355339 -0.35355339 -0.        ]
   [-0.          0.          0.        ]]]


 [[[-0.35355339 -0.35355339  0.        ]
   [-0.35355339 -0.35355339 -0.        ]
   [-0.          0.          0.        ]]]


 [[[ 0.35355339  0.35355339  0.        ]
   [ 0.35355339  0.35355339 -0.        ]
   [ 0.         -0.          0.        ]]]]


In [28]:
K_Test4 = FrameStiffness(  1 , 1 , 1 , (0,0)  , (0,1))
print( K_Test4)

[[[[ 12.  -0.  -6.]
   [ -0.   1.   0.]
   [ -6.   0.   4.]]]


 [[[-12.   0.   6.]
   [  0.  -1.  -0.]
   [ -6.   0.   2.]]]


 [[[-12.   0.   6.]
   [  0.  -1.  -0.]
   [ -6.   0.   2.]]]


 [[[ 12.  -0.   6.]
   [ -0.   1.  -0.]
   [  6.  -0.   4.]]]]


In [29]:
K_Test5 = FrameStiffness(  1 , 1 , 1 , (0,0)  , (1,0))
print( K_Test5)

[[[[  1.  -0.  -0.]
   [ -0.  12.   6.]
   [ -0.   6.   4.]]]


 [[[ -1.   0.   0.]
   [  0. -12.  -6.]
   [ -0.   6.   2.]]]


 [[[ -1.   0.   0.]
   [  0. -12.  -6.]
   [ -0.   6.   2.]]]


 [[[  1.  -0.   0.]
   [ -0.  12.  -6.]
   [  0.  -6.   4.]]]]


Validation

Beam 
<img src="Figures/W04-3-ValidationForFrameGloballStiffness.png" height = 10>

In [73]:
E =  21*10**7
A = 334*10**(-5)
I = 214*10**(-7)
I_node = (0,3)
J_node = (3,3)
K_2 = FrameStiffness( E , A , I , I_node  , J_node)
print( K_2)

[[[[ 233800.               0.              -0.        ]
   [      0.            1997.33333333    2996.        ]
   [     -0.            2996.            5992.        ]]]


 [[[-233800.              -0.              -0.        ]
   [     -0.           -1997.33333333    2996.        ]
   [      0.           -2996.            2996.        ]]]


 [[[-233800.              -0.               0.        ]
   [     -0.           -1997.33333333   -2996.        ]
   [     -0.            2996.            2996.        ]]]


 [[[ 233800.               0.               0.        ]
   [      0.            1997.33333333   -2996.        ]
   [      0.           -2996.            5992.        ]]]]


Column

<img src="4-ValidationForFrameGloballStiffness.png" height = 10 >

In [72]:
E =  21*10**7
A = 334*10**(-5)
I = 214*10**(-7)
I_node = (0,0)
J_node = (0,3)
K_1 = FrameStiffness( E , A , I , I_node  , J_node)
print( K_1)

[[[[   1997.33333333       0.           -2996.        ]
   [      0.          233800.               0.        ]
   [  -2996.               0.            5992.        ]]]


 [[[  -1997.33333333      -0.           -2996.        ]
   [     -0.         -233800.               0.        ]
   [   2996.              -0.            2996.        ]]]


 [[[  -1997.33333333      -0.            2996.        ]
   [     -0.         -233800.              -0.        ]
   [  -2996.               0.            2996.        ]]]


 [[[   1997.33333333       0.            2996.        ]
   [      0.          233800.              -0.        ]
   [   2996.              -0.            5992.        ]]]]


## Assembling the system stiffness matrix

<img src="Figures/W04-5-SystemStifnessMatrixAssemble.png" width= "70%" >

In [74]:
print(K_1, K_2)

[[[[   1997.33333333       0.           -2996.        ]
   [      0.          233800.               0.        ]
   [  -2996.               0.            5992.        ]]]


 [[[  -1997.33333333      -0.           -2996.        ]
   [     -0.         -233800.               0.        ]
   [   2996.              -0.            2996.        ]]]


 [[[  -1997.33333333      -0.            2996.        ]
   [     -0.         -233800.              -0.        ]
   [  -2996.               0.            2996.        ]]]


 [[[   1997.33333333       0.            2996.        ]
   [      0.          233800.              -0.        ]
   [   2996.              -0.            5992.        ]]]] [[[[ 233800.               0.              -0.        ]
   [      0.            1997.33333333    2996.        ]
   [     -0.            2996.            5992.        ]]]


 [[[-233800.              -0.              -0.        ]
   [     -0.           -1997.33333333    2996.        ]
   [      0.           -2996.

In [71]:
K_1[3]

array([[[  1997.33333333,      0.        ,   2996.        ],
        [     0.        , 233800.        ,     -0.        ],
        [  2996.        ,     -0.        ,   5992.        ]]])

**Short-cut for system stiffness matrix**

K = [[K_1[0],K_1[1], np.zeros(3,3)],
    [[K_1[2],K_1[3]+K_2[0],K_2[1]],
    [[np.zeros(3,3),K_2[2],K_2[3]]]

In [92]:
K = [
    [K_1[0],K_1[1], np.zeros((3,3))],
    [ K_1[2],K_1[3]+K_2[0],K_2[1]],
    [ np.zeros((3,3)),K_2[2],K_2[3]]
    ]

In [93]:
K[0]

[array([[[  1997.33333333,      0.        ,  -2996.        ],
         [     0.        , 233800.        ,      0.        ],
         [ -2996.        ,      0.        ,   5992.        ]]]),
 array([[[  -1997.33333333,      -0.        ,   -2996.        ],
         [     -0.        , -233800.        ,       0.        ],
         [   2996.        ,      -0.        ,    2996.        ]]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])]

In [94]:
K[1]

[array([[[  -1997.33333333,      -0.        ,    2996.        ],
         [     -0.        , -233800.        ,      -0.        ],
         [  -2996.        ,       0.        ,    2996.        ]]]),
 array([[[235797.33333333,      0.        ,   2996.        ],
         [     0.        , 235797.33333333,   2996.        ],
         [  2996.        ,   2996.        ,  11984.        ]]]),
 array([[[-233800.        ,      -0.        ,      -0.        ],
         [     -0.        ,   -1997.33333333,    2996.        ],
         [      0.        ,   -2996.        ,    2996.        ]]])]

In [95]:
K[2]

[array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[[-233800.        ,      -0.        ,       0.        ],
         [     -0.        ,   -1997.33333333,   -2996.        ],
         [     -0.        ,    2996.        ,    2996.        ]]]),
 array([[[233800.        ,      0.        ,      0.        ],
         [     0.        ,   1997.33333333,  -2996.        ],
         [     0.        ,  -2996.        ,   5992.        ]]])]

**Right Way**

In [100]:
K1_node=[1,2]
K1_node

[1, 2]

In [99]:
K2_node=[2,3]
K2_node

[2, 3]

Remembet the node mapping and construct the system stiffness matrix accordingly.

Let's discuss next week!